data:
  labeled_test_dir: from_preprocessor/images/test
  unlabeled_test_dir: from_preprocessor/images/test
  source_dirs:
  - data/PetImages/Cat
  - data/PetImages/Dog
  train_dir: data_processed/train
  test_dir: data_processed/test
  test_split_ratio: 0.2
model_params:
  name: resnet50
  pretrained: true
  local_weights_dir: pretrained_models
data_params:
  image_size: 224
  batch_size: 32
  num_workers: 4
train_params:
  epochs: 5
  finetune_epochs: 3
  learning_rate: 0.001
  optimizer: AdamW
  scheduler:
    name: None
    params:
      T_max: 10
outputs:
  base_dir: outputs
  log_file: '{run_folder}/run.log'
  model_path: '{run_folder}/best_model.pth'
  report_path: '{run_folder}/results_report.pkl'
  cm_plot_path: '{run_folder}/confusion_matrix.png'
  submission_file: '{run_folder}/submission.csv'
  training_curves_plot_path: '{run_folder}/training_curves.png'
  model_path_finetuned: '{run_folder}/best_model_finetuned.pth'
  report_path_finetuned: '{run_folder}/results_report_finetuned.pkl'
  cm_plot_path_finetuned: '{run_folder}/confusion_matrix_finetuned.png'
  training_curves_plot_path_finetuned: '{run_folder}/training_curves_finetuned.png'
