# augment_config.yaml
seed: 42

data:
  # CSV with at least: filepath,label,split
  manifest_csv: "manifest_full_processed_rel.csv"
  # If filepaths in CSV are relative, they are relative to root_dir (optional)
  root_dir: "./"
  # which splits to augment (default: ['train'])
  splits: ["train"]

aug:
  per_image: 2             # how many augmented variants to generate per input image
  preset: "medium"         # one of: light | medium | strong
  img_size: [224, 224]     # H, W

output:
  dir: "preprocessed_data/augmented"
  keep_label_dirs: true    # if true, images are saved in class subfolders under output.dir
  format: "jpg"            # jpg | png | webp
  jpeg_quality: 95         # used if format == jpg
  manifest_csv: "manifest_full_processed_rel.csv"  # where to write merged manifest (optional)
  overwrite: false

# Deterministic preprocessing before augmentation
manipulation:
  to_float:
    enabled: false
    max_value: 255.0
  size:
    mode: "letterbox"   # "letterbox" | "resize" | "none"
    letterbox:
      target_hw: [640, 640]
      pad_value: [114, 114, 114]
    resize:
      size: [640, 640]

# Deterministic enhancement before augmentation
enhancement:
  denoise:
    type: "none"        # "none" | "median" | "gaussian" | "bilateral" | "nlm"
    median:
      blur_limit: 3
    gaussian:
      blur_limit: 3
      sigma: 0
    bilateral:
      d: 7
      sigma_color: 75
      sigma_space: 75
    nlm:
      h: 7
      template: 7
      search: 21
  contrast:
    type: "none"        # "none" | "clahe" | "equalize"
    clahe:
      clip_limit: 2.0
      tile_grid_size: [8, 8]
  gamma:
    enabled: false
    gamma_value: 1.0
  sharpen:
    enabled: false
    alpha: 0.25
    blur_limit: 3
  to_float:
    enabled: false
    max_value: 255.0
